# Generated by Django 6.0.6 on 2026-06-08 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('villagers', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='VillagersModel',
            new_name='Villager',
        ),
    ]
