# Generated by Django 6.0.6 on 2026-06-09 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hosteller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostel_no', models.PositiveIntegerField()),
                ('room_no', models.PositiveIntegerField()),
                ('name', models.CharField(max_length=30)),
            ],
        ),
    ]
